# On recursive analytic affiliation: reflecting on the altered conditions of ethnographies of coding

## Introduction

I report here on a deliberately naive attempt to re-count a single number: approximately 29 million code repositories on [Github](http://github.com)  at a particular point in time (late 2015). The number appeared in a research  project primarily focused largely on transformations in the social life of coding, programming and software development.  The project  sought to experiment with data-intensive methods, infrastructures and tools -- cloud computing services such as Google Compute, data analytic and visualization tools such as `R,` `Python` and `IPython` notebooks, large data stores such as` BigQuery`, streaming data from social media platform APIs (Application Programmer Interfaces), predictive models especially in the form of machine learning classifiers (support vector machines, Naive Bayes classifiers, random forests) --  in making sense of what happens on  Github *en masse.[^12]*  Somewhat recursively (although I don't want to make too much of this recursion, since I do not think it amounts to a recursive public [@Kelty_2008]), Github happens to be the media platform that hosts the development of many of these tools and infrastructures, and it also directly hosts  all of the text, code, figures, intermediate results and configuration information for the research project itself [@Metacommunities_2016].

The approximate number 29 million  will in this chapter serve as a synecdoche for big data. The number, a count of all the repositories on Github in late 2014, is a part standing in for the whole. Conversely, since it presents itself as the total of all repositories on Github at a given moment, it is itself a cardinal number, a whole, standing in for the totality. The story of an encounter with this single number will, I hope, evoke and exemplify the appeal, frustrations, hopes and some material configurations associated with contemporary data practices that envision working with 'all the data' [@Mayer-Schonberger_2013]. This number, one of a series of similar numbers,  exists and exerts effects in different ways on counting and accounting. I'm interested in its composition, its instability, the 'stories,' imaginings and materialisations it authorises, and its problematic relation to big data infrastructures.

What kinds of engagement can we have with such numbers today amidst perhaps their deep transformation and re-materialisation in technologies? Given so much computational counting, so many efforts to count all manner of things (species, clicks,  stars, likes, cells and bitcoin transactions), and indeed strong injunctions to tell stories about such numbers, what can social researchers do? The key difficulty in developing an ethnographic sensibility around such numbers resides in the many detours, variations and differences they embody, not least for the social researcher who finds him or herself trying to re-count them or account for them. 

While I'm very drawn to attempts to count things and to weave counts into ethnographic accounts, during this project I often wondered about how to count things whilst paying attention to their composition. Numbers and counts are site of entanglement between device-specific materialities and imaginaries of order, totality, rank, inclusion, boundary and power.  This double sense of numbers as both a calculatively ordered cutting-framing-summing-up and as materially specific figuring of differences could well be understood in terms of what Lucy Suchman's describes as a 'configuration': 

>the device of _configuration_ has two broad uses. First, as an aid to delineating the composition and bounds of an object of analysis, in part through the acknowledgment that doing so so is integral not only to the study of technologies, but to their very existence as objects. And second, in drawing our analytic attention to the ways in which technologies materialize cultural imaginaries, just as imaginaries narrate the significance of technological artefacts. Configuration in this sense is a device for studying technologies with particular attention to the imaginaries and materialities that they _join together_, an orientation that resonates as well with the term's common usages to refer to the conjoining of diverse elements in practices of systems design and engineering [@Suchman_2012, 48].

While Suchman's examples of configuration come from software systems, I'm suggesting that a single number -- 29 million repositories on Github -- could be re-counted as a configuration. The argument is that even the listing, enumerating and counting of things in a single number can be seen as a configuration. 

## Re-counting a capital number on  a platform

On Github, two numbers have cardinal and indeed capital importance:  the number of people using the platform, and the number of different code repositories stored there.  I deal in this chapter only with the latter.   The  counting I undertake will focus on problems of copying, duplicating, and imitation that render large numbers a moving substrate.

Github, started in in 2007, epitomises and has indeed been central -- as the suffix 'hub' suggests -- to a mass of configurational events associated with the development of big data practices. Like many social media platforms,  it has grown tremendously in the last 7 years  to include around 38 million software projects (September 2016). This growth flows from a tremendous variety of processes that are difficult to summarise or classify partly because the actors, topics or domains of coding are so diverse and partly because much of what flows through Github is both technically and socially 'innovative' in the sense that Bruno Latour uses the term: '" innovative" means that we do not know the number of actors involved in advance' [@Latour_1996, 72]. 

Amidst this morass of code, configuration work, copying, collaborating, and much playing around,  Like many contemporary assemblages, Github seeks to describe itself through large numbers. We might call these  'capital numbers' since they serve a vital function in attracting investment, imbuing the platform with hub-like importance in contemporary innovation systems, and actually, as I will soon suggest, directly support the injunction to 'tell stories with the [big] data.'  These numbers in their sometimes daily changes and updates attest to an investment in being innovative or open-ended enumerations.  

As Suchman's concept of a configuration suggests, capital numbers combine with cultural imaginaries in manifold ways.   In June 2014, the Github 'about' page showed a photo of a women working in an urban office location, with lights and professional camera focused on her work. It described '6.1 million people collaborating right now across 13.2 million repositories ... building amazing things together' [@Github_2014a]. In late November 2015, the same page has a slightly more functional description, and the image seems to be of a press conference in China:

>GitHub is how people build software. With a community of more than 12 million people, developers can discover, use, and contribute to over 29 million projects using a powerful collaborative development workflow. [@Github_2015](https://web.archive.org/web/20151216055610/https://github.com/about)

The numbers change over time alongside the composition of the actors involved (women coding and working at Github, a sore point for the company as a co-founder was involved in sexual harassment complaints; Chinese developers using Github, but also political activists, leading to a denial of service attack on the Github, allegedly by the Chinese government [^3]). But the changing numbers, alongside the sometimes rather sublime scales of community (a 'community' of 12 million people?) certainly form part of Github's description.


## The litany of sense-making: enumerating the aggregate through events

In 2013, a time in which the injunction to do things with data was impacting social science research funders as well as many people in media, commerce, industry and government,  my data-analytic ambition was that I could critically  re-count the capital numbers -- people and repositories on Github -- in some way. I planned to use data analytic methods to count people and count things, in this case, software projects on Github. In re-counting them, I wanted to en-counter something of their composition in all its heterogeneity and conformity, to show how their scale was an effect of specific dynamics of imitation, and perhaps to suggest that such numbers were highly performative in essence.  This would be a both political and culturally significant since those numbers are typical of social media platforms and their capitalisation. 

How could I  actually count software project or people? Like everyone else, I turned to data published through the Github API (Application Programmer Interface). APIs  were not created as a data resource for social scientists, but for software developers working in convergence cultures [@Jenkins_2004] in which connecting different platforms, devices, sites and practices together using code has become standard practice, APIs have great practical significance [@Bucher_2013]. In Github's case, data published through the API derives from acts of writing and reading code (although not only code -- an extraordinary variety of other documents, texts, images, maps, and other forms of data can be found on the platform).   The data is logged  as developers write code and move  that code in and out of code repositories using the `git` version control system [@Git_2014]. Coding today constructs and take place in increasingly complex associative infrastructures.  Github seeks to figure coding as a social network practice based on a hub.

By convention much API data from social media sites has an 'event' structure that links named actors and named entities to specific infrastructural locations (usually coded as an URL) at a particular time (the 'timestamp'). While not all big data has this timestamp-actor-location-links texture, it is common enough to stand in as typical of the data that big data infrastructures and practices encounter.  

```
{
"id": "2111998059",
"type": "WatchEvent",
"actor": {
"id": 1459103,
"login": "mmemetea",
"gravatar_id": "4532d1e4885f579ca7d9aa8748418817",
"url": "https://api.github.com/users/mmemetea",
"avatar_url": "https://avatars.githubusercontent.com/u/1459103?"
},
"repo": {
"id": 14802742,
"name": "OpenSensorsIO/azondi",
"url": "https://api.github.com/repos/OpenSensorsIO/azondi"
},
"payload": {
"action": "started"
},
"public": true,
}
```

What would it mean to count things using this data? These records conjoin elements together.  The relatively simple  `WatchEvent` on Github shown in the data extract above documents how an `actor` calling themselves `mmemetea` associates as a `Watcher` with a  repository called `azondi`, a software project coordinated by the 'organisation' `OpenSensorsIO`.[^2]  Note that the event also has various attributes -- it is a `public` event, it has a 'payload' (often much more complicated than simply `started`) -- and includes various indexical references or `id`s that link the event to other groups of people, organisations, repositories and images (`gravatar_id`). The intricate  syntax of this data -- many brackets, inverted commas, colons, commas -- attests to a complex social configuration which links actors, actions, places and times in discrete events ordered in time. The discreteness of components in this event - actor, organisation, repository, payload, gravatar, etc. --  attests to the potential for the precise configuration of elements around a given repository to change or rearranged in some way. New actors might be added; relations might appear between entities; the location of entities might shift, and forms of association ('organizations') might subsume or grow out or around all of this. In short, each event in the timeline API suggests another small re-configuration in the totality of elements comprising Github. 

## Imbuing numbers with importance

When our project started in 2012, we were clearly not the only people interested in counting things amidst the massive stream of event data concerning Github. A dataset purporting to contain the whole public event timeline of Github suddenly appeared in mid-2012. Ilya Grigorik, a 'Web Performance Engineer' at Google, launched a Github repository `igrigorik/githubarchive` linked to a website `GithubArchive.org` dedicated to archiving all the Github API public event data -- the so-called 'timeline' --  in one place [@Grigorik_2012].  Grigorik, or `igrigorik`not only published all the data in a cloud-based data store but published that data  in Google's newly launched cloud computing service, GoogleBigQuery.[^1] The [Github timeline data](https://bigquery.cloud.google.com/table/githubarchive:github.timeline) was listed, along with all the words in Shakespeare and all the US birth name records, as one of three dataset exemplars that people could use to learn about Google `BigQuery` [@Google_2016]. Like the data on GithubArchive itself, the Google `BigQuery` copy of the Github public timeline data was updated hourly. Reaching back to  2011, it logs around 400 million public events.

The archiving, copying and transformation of Github event data into  big data-ready format drew the attention many people. The data was publicised through several 'Github Data Challenges' (2012-2014). Working to count events in different ways using data analytic techniques and data visualizations, people re-counted events on the Github timeline to in order to tell different 'stories' about Github's millions of repositories and people.   These stories include many different configurations. For instance,  the 'OpenSource Report Card' (http://osrc.dfm.io/)  or `dfm/osrc` by Dan Foreman-Mackay [@Foreman-Mackay_2014], is a prize-winning use of the timeline data (see Figure \ref{fig:osrc}). It ingests all the data from the Githubarchive, counting what developers do, when they do it, and using what programming languages. With this data stored, it then builds a predictive model that allows it to both profile a given Github user in terms of the mixture of programming language they use, and to predict who that Github user might be similar to. Here the mass of events in the Github timeline are brought to bear on finding similarities between people, producing numbers and score to suggest similiarities in coding work. 

In response to the Github Data Challenge in 2012, people looked for feelings or 'sentiments'  about different programming languages in the timeline data.  Feelings associated with coding were mined by counting emotional words present in comments accompanying the Github events (http://geeksta.net/geeklog/exploring-expressions-emotions-github-commit-messages/). The presence of words in these message can be cross-linked with programming languages in order to profile how different programming languages elicit different emotional reactions. 

Capital numbers were also *nationalised* or regionalised. People  mapped coders and repositories by geographic location. The  mapping of Github contributions by location performed by David Fischer (http://davidfischer.github.io/gdc2/#languages/All) is typical in that it too counts events, but this time puts the emphasis on the geography of the 'top' repositories, coders and their programming languages. As the David Fischer puts it 'this data set contains contributions to the top 200 GitHub repositories during the first four months of 2013 and plots the location based on what the contributor provided' [@Fischer_2013a].  

*Logistic numbers* can be derived from the data streams. People made live dashboards, a characteristic data analytic visual form, for Github. `Octoboard` (http://octoboard.com/) animates changes on Github using the timeline data [@Roussell_2015] (see Figure \ref{fig:octoboard}). It ornaments the capital numbers with a range of peripheral live enumerations that point to the liveliness of events on Github. It presents a summary of daily activity in major categories on Github – how many new repositories, how many issues, how repositories have been 'open sourced' today. It offers realtime analytics on emotions. Like many other dashboards associated with social media analytics, `octoboard` suggests that the constant change in associations and projects in software development can no longer be known through leisurely rhythms of analysis, but is increasingly framed as  a problem  realtime awareness. 

Looking slightly more widely, the Github timeline data has quickly become a favourite training tool for data mining textbooks books that configure and convey the calculative agencies characteristic of capital numbers. In  *Mining the Social Web: Data Mining Facebook, Twitter, LinkedIn, Google+, GitHub, and More,* Matthew Russell makes use of the Github timeline to demonstrate ways of uses social network analysis to highlight the important nodes and links between repositories and users [@Russell_2013]. Finally and not least for my own projects, academic researchers in computer science and certain parts of management science, GithubArchive and the `BigQuery` publication of Github  has been a boon because it permits relatively easy  study technologically and economically important practices of software development.  Academic researchers in fields such as software engineering do social network analysis in order to gauge productivity, reuse, efficiency and other engineering and management concern [@Thung_2013]. Like the many Github-hosted projects discussed above, they analyse sentiment [@Guzman_2014], collaboration and productivity [@Dabbish_2012], and geography [@Takhteyev_2010].

All of these re-countings enliven, animate, reactivate, localise and qualify the capital numbers by carving off fragments from the 'natural multiplicity' [@Badiou_2008, 211] of the aggregate. They potentialise the numbers in terms of work, geography, liveness  and further accumulation by summing them up in different ways (realtime, networks of connections, geographies of work and affect).   

## Acts of imagined configuration

How could we re-count capital numbers in order to both further highlight their dynamic composition through flows of association and to highlight some of the highly reactive, imaginary boundary work they might do? Could configurative numbers in both their compositional and imaginary-materialising multiplicity be counted? Whilst there is a much configurational work involved even in beginning to count things heterogeneously on an infrastructural scale, I found myself drawn in two directions, one concerned with ephemerality of configurations and the other with their imitative composition. 

The vast majority of repositories on Github are highly ephemeral. They attract one or two events. A small number of repositories, counted on the lower right-hand side of the plot capture many thousand events. A great proportion of events in the timeline data were absorbed into ephemeral repositories (if that is not too great a contradiction in terms).  Millions of repositories flash into visibility on the timeline for a brief period before falling back into obscurity. They remain in the capital number. The diagram shown in the Figure \ref{fig:power_time} encapsulates this imitative flux. On the left hand side, millions of repositories receive less than five events during the 18 months. On the right hand side, less than 50 repositories receive more than a thousand events. A similar pattern appears in the other capital number: while some 'people'  emit many thousands of events, others only trigger a few.[^5] Already, then, the capital number of repositories on  Github takes on a different composition when viewed from the perspective of duration.

But rather than see this ephemerality as waste, noise or something to be discarded, we might trace the working of associative processes through it. I can only give a brief indication of this here. For instance, counting just the unique names of repositories in the timeline data, counting how often and when they appear in events,  begins to show how associations are configured on Github. Almost one half of the repositories in Github inject only one event into the timeline data stream. What is this event? The act of copying ('forking') another repository. People 'fork' other repositories frequently. Table 1 shows 10 million ForkEvents, suggesting that around one third of the total 29 million repositories are direct copies.  Acts of copying occur on many scales and at various levels of infrastructural and associative complexity. This copying is vital to the 'sharing' practice of Github coding. Of the several hundred million events in the timeline dataset, approximately 95 million result from copying, watching, commenting on or directly participating in other repositories.   

It is hard to grasp the texture of imitative processes in event data. We can view localised aspects  of propagation of imitation. Both Figure \ref{fig:bootstrap_forks} and \ref{fig:android_forks} count imitations in the form of copying code, but in ways that go beyond the formal copying mechanisms offered by Github itself (for instance in the 'Fork' button that appears on the top right hand side of any repository on Github; for example [https://github.com/twbs/bootstrap](https://github.com/twbs/bootstrap)). Imitations appears in two different ways in these figures. The broad bands of color rippling horizontally  across the middle of the figures graph the counts of copies being made each day on Github of popular repositories using the Fork action. (In forking, the repository name remains the same.)   But the much more dense striations  on either side of the central bands, seen for instance in Figure \ref{fig:android_forks}, count repositories whose names incorporate the important repository, but vary it in some way. These repositories have some association with the `android` repository, but diverge from it in a multiplicity of ways. A repository may, for instance, relate to the popular  Twitter `bootstrap` repository yet combine it with a range of other platforms and devices such as `android` or `jQuery`. 

In striated zones of associative imitation, it is possible to count something different. Imitations augment the average everydayness of coding work with forms of associative investment and affective identification.  In this work, important repositories act as high visibility markers around which forms of identity take hold and multiply. Unlike the capital numbers with their total aggregates of people or repositories, the imitative fluxes that bulk out and pad in these diagrams have diverse network-making configurations.  The implication here is that by counting elements within the capital numbers, we can begin to glimpse the pathways of generative circulation that enliven and literally join together in contemporary technologies.     

## De-capitalising configuration

The very act of counting these imitations has a device-specificity, in its reliance on the Github platform API, the GithubArchive timeline dataset and the GoogleBigQuery cloud analytic's platform, and indeed Github itself as the repository of the code and text comprising this article [@Metacommunities_2016]. Unlike the network-tracing approach, it can perhaps take into account the ways in which the platform itself works to shape networked associations. Whenever we count or calculate in any form, device-specific configurations materialise in the numbers.  The expansively contagious nature of imitation inevitably encounters device-specific configurations.       

One sense of how numbers embody device-specific configurations can be seen by examining high event-count repositories on Github.  The top 1000 repositories attract around `r round(total_events/290000000 * 100)`% of all events in the timeline period. The query de-capitalises the repository names for the purposes of aggregation (e.g. a repository called `DotFile` will be counted along with `dotfile`). Given the flattening of the names to lower case produced by this query, we cannot readily see how those events are distributed. But these highly frequented repositories, which only comprise a tiny percentage of the 29 million on  Github, absorb many events. What happens in these high event count repositories? 
 
Several major traits appear in these high event-count repositories. Many events come from off-platform. Github, despites its own figuration as a hub or as the capital, functions as an element in others configurations, located elsewhere.   For instance, the repository `eclipse.platform.common` accounts for almost 2 million events in the timeline data. A single repository attracting two million events (or almost 1% of the total event count in the timeline data)  suggests something highly significant in the geography of coding work. Perhaps the fact that `eclipse` is itself part of the Eclipse Foundation,  'an amazing open source community of Tools, Projects and Collaborative Working Groups' [@EclipseFoundation_2016] with almost a thousand of its own projects, might help explain the large number of events. More significantly, the high-frequency event trade in `eclipse.platform.common` is an example of how Github itself functions as part of a configuration.  The `eclipse` repositories are not actively developed on  Github. They are mirrored  or themselves copied from the hundreds of `git` repositories found at (git://git.eclipse.org)[git://git.eclipse.org]. Like many other significant repositories (`linux`, `android`, `mozilla`, `apache`), high event counts figure Github as a hub. 

In addition, even where events do originate on Github, many of them concern Github or  technical configurations closely associated with Github.   For instance, the list of names of high-event count repositories includes many containing a set of terms centred on a few highly repeated items. On the one hand, the sharing of names -- for instance, the many repositories that contain the term `dot` as in `dotfile` or `vimdot` -- suggests the imitation or repetition that Tarde describes. On the other hand, terms like `dot`, `test`, `hello`, `config`, `doc`, `build`, `setting` or `demo` also stream through this set of repository names. Many repository names proliferate from these stems. All of these stems relate to device-specific configurations and work done to sustain the configuration of devices in particular places. 


## Conclusion

Capital numbers, I have suggested,  enumerate an aggregate, imbue it with importance linked to infrastructural scale and complexity, and promise to generate further accumulation. As we have seen, the capital numbers attract many further aggregations in the form of data archives (GithubArchive) and oligoptic visualization. Configurative numbers, in resonance with the configuration work that gives rise to them, account for the both the accumulation and the heterogeneity of events, people and things, and for their re-counting. 

It takes work to get contemporary digital data and associated large numbers to do something other than add to the count of capital numbers and their platform-centred aggregates.  Configurative numbers, I have suggested, as one term for the versions of enumeration that result from such re-countings. We saw how that re-counting points to imitative fluxes, to that which takes places elsewhere but is refracted in the capital numbers, and to device-specific configurations that saturate the data stream. None of this discounts the capital numbers -- 29 million, 12 million -- as if they were false, reactive or performative numbers [@Espeland_2008]. 

How do we re-animate the capital numbers that abound in contemporary technologies? To do this, we need to find ways of working on formatted data that goes against its pre-formatted accounting.  Device-specific research that attends to the ways in which data is formatted, and how that formatting itself materialises imaginaries of inclusion, relation and wholes that pertain more broadly. At the same time, paying attention the configuration or device-specific composition of numbers, we can construct a view on what remains irreducible to the formatted imaginaries of the data-stream. 

