library(jsonlite)
library(ggplot2)
library(dplyr)
j = stream_in(file('data/jobs.json'), flatten=TRUE)
colnames(j) 
s=round(sum(na.omit(as.numeric(j$statistics$totalBytesProcessed)))/1e12, 1)
print(s)

bytes = as.numeric(j$statistics$totalBytesProcessed)
dates = as.Date(as.POSIXct(as.numeric(j$statistics$creationTime)/1000, origin="1970-01-01"))
df= data.frame(date = dates, vol = bytes)
gbday = df %>% na.omit  %>% arrange((date)) %>% mutate(gbcumul = cumsum(vol/1e9)) %>% group_by(date) %>% mutate(job_count = n())
head(gbday)
dl = data.frame(x = c(as.Date('2016-07-31'), as.Date('2013-08-13')), y =c(80000,13500) , labs = c(paste(as.character(s), 'terabytes'), '13500 jobs ran overnight')) 
g= ggplot(gbday, aes(x=as.Date(date), y=gbcumul)) + geom_line()  + ggtitle('Gigabytes/day on BigQuery jobs') + ylab('Gb of data (cumulative)') + xlab('')
as.character(s)
g = g + geom_text(data=dl, aes(x=x, y=y, label=labs, group=NULL))
g
