
---
title: "48 million configurations and counting: capital numbers and technical ensembles"
author: "Adrian Mackenzie"
date: "`r Sys.Date()`"
output:
tufte::tufte_handout: default
citation_package: biber
latex_engine: xelatex
bibliography: /home/mackenza/ref_bibs/uni.bib
link-citations: yes
header-includes:
    - \usepackage{setspace}
    - \doublespacing
---

# Abstract

Technical ensembles such as social network sites, online content management systems, streaming media platforms, mobile communication systems, scientific models, supply chain logistics management solutions, or cryptocurrency systems constitute an increasingly large yet relatively obscure zone of contemporary cultures. 
This paper examines attempts to enumerate the elements of such technical ensembles by counting, mapping or listing them.
Via a case study of a large technical ensemble -- the code repository Github.com -- that itself hosts the ongoing software development for many contemporary digital technical ensembles, it analyzes how such enumerations align themselves to the capitalization of the  technical ensemble.
As an alternative to this capitalization, the paper proposes a configurative enumeration of elements of technical ensembles.
In a configurative enumeration, the diverse composition, the rhythms of imitation, variation and commutation, and the constant tuning, repairing and adjusting of technical elements crucial to the ongoing existence of technical ensembles comes into view.
An orientation and attunement to configuration, the paper suggests, provides an alternative critical affirmation of the inventive realities of technical ensembles, without simply re-iterating their capitalization. 

# Introduction

The reality of technical ensembles is difficult to engage with sociologically. At macro-scale, large  technical ensembles are highly prominent forms of organisation of economic and cultural life. We need only think of Facebook with 1.6 billion users as an example of a technical ensemble.  Its  effects on work, sociality, political  or cultural practices are widely discussed and debated.  At the micro-scale of individual experiences, such platforms largely disappear as ensembles, even as their interfaces and their terminals absorb large parts of people's lives in on-screen attention. Technical ensembles largely comprise an obscure central zone of practices, objects, processes and systems. Concepts of infrastructure, device, media and assemblage struggle for analytic purchase on this central zone of technical ensembles, a zone where combinations of sub-ensembles, machines, platforms, tools, processes of invention, practices of work, technical, geographical, social and energetic materialities entwine in manifold ways.  Importantly, large technical ensembles have temporalities of concretisation and abstraction, of oriented mutations and adaptation, that cannot be easily conceptualised in terms of tools, machine or infrastructures. They have a collective and social order that is not hierarchically organised, nor purely lateral flow. Today, their associative, imitative and often highly layered fabric owes much to the forms of software development or coding  woven through them. 

The difficulty of engaging with technical ensembles stems, if Gilbert Simondon is right, from the way in which the reality of technical objects has increasingly crystallised in collections of technical elements such as tools and machines [@Simondon_1989, 81]. In these collections, the reality of the ensemble can be expressed neither in the figure of the proprietor, the executive or chief operator (which in the case of Facebook would be  Mark Zuckerberg), nor in the figure of the myriad workers and users attached to the ensemble (who in the case of Facebook could well be any reader, whether they use Facebook or not [@Marshall_2016]). Neither property nor labour  access the configured and concrete operational reality of the technical ensemble, according to Simondon, because they both tend to treat the ensemble as an individual technical object, not as an ensemble or  as a mutable configuration, and mold perceptions of the technical ensemble according to either the utility or exchange value. 

# A technical meta-ensemble

Assuming that technical ensembles do have a configured operational reality, how would we engage with it sociologically? This paper reports on an  attempt to re-count a single large number, currently standing at 48 million, associated with the collective existence of contemporary technical ensembles. The number 48 million concerns the number of code repositories on the social media platform Github. The number stands in or represents what happens on  Github: coding or software development. 'Github is how people build software' according to Github  [@Github_2015]. While it is itself a technical ensemble, for present purposes, Github is not itself the focus. Rather the millions of coding projects and millions of developers assembling around the Github  are the focus. Github  is a place where the obscure central zone or reality of technical ensembles might be more productively analyzed.

Github  instances key shifts in the way that technical ensembles aggregate, concretise and change over time. These shifts are heavily linked to coding practices.  Coding practices have changed over the last decade or so in several profound ways. The organization of software development has shifted away from individual machine-centred software development (the kind epitomised by Microsoft Windows or IBM mainframe software during the latter part of last century [@Campbell-Kelly_2003; @Ensmenger_2010]) to a much more de-centralized architectures of varying scope threaded across into communication and network infrastructures. Second, added to this global geography of coding, an explosion of digital devices and infrastructures, ranging from proliferating mobile devices and sensors to mushrooming data centres,  have widened the reach and variety of coding. Code circulates and addresses many more elements of the equipmental totality [@Heidegger_TBA]  - cameras, doors, cars, books -  than it did at the turn of the 21st century. Third, the lines and borders separating the production, distribution, and operation of code in technical ensembles have thoroughly blurred. Code flows in much more diverse ways through infrastructures and devices. For instance, 'devops' (development-operations) deploys frequently revised code directly into the ongoing transformative-maintenance of information infrastructure through continuous deployments, often directly from code repositories on sites such as Github [@Mackenzie_2016b].  Fourth, although the geography of coding work still centres on well-established urban centres such as San Francisco and London [@Mackenzie_2016], but by virtue of a much wider distribution of coding tools and skills, occurs in many other places as well. Finally, across all of these changes, coding has become a much more *public* economic and cultural activity (see [@Kelty_2008]), and the *publicness of code* has become a major concern for business, art,  government and science, albeit for different reasons (for instance, in scientific work, open data has been accompanied by a rapid proliferation of techniques, resources and tools for publishing code written for scientific purposes; for instance, in the many attempts to train school students and others to code as a putative 'basic life skill'). These five tendencies in coding work, all of which traverse and structure Github itself, perhaps merit much closer attention. But I offer them here as a way of signalling some of the complexities involved in making sense of contemporary technical realities. Github, we might say, is a technical meta-ensemble because it intensifies all of these tendencies in coding and software development. 

# Capital and configurative numbers

The social media site Github, started in in 2007, epitomises and has indeed been central -- as the suffix 'hub' suggests -- to the changes in developing code and hence in the relational fabric of many technical ensembles. Like other social media platforms, it has grown tremendously in the last 7 years. This growth flows from a tremendous variety of processes that are difficult to summarise or classify partly because the actors, topics or domains of coding are so diverse and partly because much of what flows through Github is both technically and socially 'innovative' in the sense that Bruno Latour uses the term: '" innovative" means that we do not know the number of actors involved in advance' [@Latour_1996, 72]. Github's growth is not unique. Online code repositories have existed for several decades (most famously [SourceForge](http://sourceforge.net)), although more recent arrivals such Github, [BitBucket](https://bitbucket.org/), GoogleCode (which has closed and migrated to Github), [GitLab](https://about.gitlab.com/), or Gitorious tend to invite and promote collaborative coding on a larger scale.

Like many contemporary assemblages, Github has difficulty in describing its own genesis. It presents itself through large numbers such as `48 million`, and these numbers in their sometimes daily changes and updates attest to an investment in open-ended enumerations. These numbers are often accompanied by images that localise the social identity and geographic location of developers. In June 2014, the Github homepage showed a photo of a woman working in an urban office-loft (presumably San Francisco, where Github  is based), with lights and professional camera focused on her work. It described '6.1 million people collaborating right now across 13.2 million repositories ... building amazing things together' [@Github_2014a]. In late November 2015, Github has a slightly more functional description, and the image seems to be of Github founders in a press conference in China:

>GitHub is how people build software. With a community of more than 12 million people, developers can discover, use, and contribute to over 29 million projects using a powerful collaborative development workflow. [@Github_2015](https://web.archive.org/web/20151216055610/https://github.com/about)

The numbers change over time alongside the composition of the actors involved (women coding and working at Github, a sore point for the company; Chinese developers using Github, but also political activists, leading to a denial of service attack on the Github, allegedly by the Chinese government [^3]). But the changing numbers, alongside the sometimes rather sublime scales of 'community' (a 'community' of 18 million people?) in several respects only highlight and even exacerbate the difficulty of engaging with Github as a typical contemporary technical ensemble. 

[^3]: Neither image -- the woman at work in a loft-conversion office or the press conference in China -- is arbitrary, again suggesting that enumeration is always also configurative in the sense of materialising imaginaries of wholeness, difference, inclusion, etc.  Github was rocked in 2012 by allegations of sexism and mismanagement, particularly associated with one of the co-founders, who subsequently resigned and left Github [@Github_2014]. In early 2015, Github itself was subject to a massive Denial of Service attack, emanating from China. Reports alleged that the DoS attack targeted pro-democracy repositories on Github. Unlike its regulation of other social media platforms, China does not block Chinese citizens' use of Github because Github is seen as economically and commercially important for the software industry [@Marczak_2015].

Numbers such as 18 million 'people' and 48 million 'projects' do display something of the mode of existence of technical ensembles. In important ways they are part and parcel of platform politics and financial technological economies [@Gillespie_2010]. Given the capital investments that Github has attracted in the last few years (\$US100 million from the venture capital investment fund Andressen-Horowitz in 2012), these numbers affect flows of capital.  They may be somewhat 'false numbers' as Martha Lampland suggests, designed to enable certain forms of rationalization [@Lampland_2010]. They have the feel of what Carolin Gerlitz and Celia Lury describe in their study of the social reputation website Klout as 'reactive numbers' meant to evoke further work, action and engagement [@Gerlitz_2014a].  The series of numbers 29, 31, 48 million, ...   perhaps enact Github as an 'enumerated entity' [@Verran_2012, 61].

While the numbers resemble others -- population statistics for small nations, amounts of money spent on a new building, a research programme or a CEO's remuneration -- they become visible, circulate and are seen in ways that prevent them from being easily assimilated to biopolitical or financial numbers. Their salience and pluri-potence will be described further below, but already they warrant some kind of designation and differentiation. We might call them 'capital numbers.' Capital here has the triple sense of a centre ('hub'), the capital letter of a proper noun, and an accumulated fund with potential to growth.   A capital number enumerates an aggregate, imbues it with importance linked to  scale and complexity, and promises the potential to generate further accumulation.

HERE
