library(tufte)
library(bookdown)
#render('configuration_jcult_econ.rmd',output_format=tufte_handout())
render_book('configuration_jcult_econ.rmd', output_format = tufte_html2())
#render('lists_conversion_experience.rmd',output_format=ioslides_presentation)
#render('lists_conversion_experience.rmd',output_format=tintPdf())
