library(tufte)
library(bookdown)
library(tint)
render_book('configuration_jcult_econ.rmd',output_format=tufte_html())
#render('lists_conversion_experience.rmd',output_format=ioslides_presentation)
#render('lists_conversion_experience.rmd',output_format=tintPdf())
